<Project>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <Exclude>[DataLayer.Migrations]*</Exclude>
    <Exclude>[OnlineStore.Tests.Shared]*</Exclude>
    <ExcludeByFile>**/Migrations/**.cs</ExcludeByFile>
  </PropertyGroup>
</Project>