services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: onlinestore-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - onlinestore-network

  redis:
    image: redis:7-alpine
    container_name: onlinestore-redis
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - onlinestore-network

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: onlinestore-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    mem_limit: 256m
    networks:
      - onlinestore-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.115.0
    container_name: onlinestore-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    mem_limit: 256m
    depends_on:
      - jaeger
    networks:
      - onlinestore-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: onlinestore-api:latest
    container_name: onlinestore-api

    depends_on:
      - sqlserver
      - redis
      - otel-collector

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
      Swagger__Enabled: "false"

      ConnectionStrings__DefaultConnection: >-
        Server=sqlserver;
        Database=ShopDB;
        User Id=sa;
        Password=${MSSQL_SA_PASSWORD};
        TrustServerCertificate=True;

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "OnlineStoreApi"
      Jwt__Audience: "OnlineStoreClient"

      Redis__Configuration: "redis:6379"
      Redis__InstanceName: "OnlineStore:"

      OpenTelemetry__Enabled: "true"
      OpenTelemetry__Endpoint: "http://otel-collector:4317"
      OpenTelemetry__TraceSamplingRatio: "1.0"

    ports:
      - "5000:80"

    networks:
      - onlinestore-network


volumes:
  sqlserver_data:
  redisdata:


networks:
  onlinestore-network:
