name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
